"""TC-SEC-10 — TLS 1.3-only config scan (LM-ARCH-001 §17.13, §17.3), as a
repeatable pytest entry (previously asserted only in the WP-08 real-process
smoke; the security README noted "a repeatable pytest entry follows the TLS
serving work" — this is that entry).

A REAL TLS server is started on 127.0.0.1:<ephemeral> with the SAME context
builder the CLI wires into uvicorn (`security.tls.build_tls13_server_context`,
§17.3), using an identity generated by the §17.3 generator in a tmp dir:

  1. a TLS 1.3 client completes the handshake; the negotiated version is
     "TLSv1.3" and the cipher is one of the three TLS 1.3 suites;
  2. a TLS 1.2-only client is REJECTED at handshake (fails closed, both
     sides see the failure — no silent downgrade);
  3. the production context builder pins `minimum_version` to
     `TLSVersion.TLSv1_3` (config scan; no upper bound needed — TLS 1.3 is
     the protocol ceiling).

No privileged ports, no external service: everything is loopback + tmp dir.
"""

from __future__ import annotations

import socket
import ssl
import threading
import time
from collections.abc import Iterator
from pathlib import Path

import pytest

from localmesh_agent.security.tls import build_tls13_server_context, load_or_create_identity

# The three TLS 1.3 cipher suites (RFC 8446); OpenSSL supports all three here.
TLS13_CIPHERS = {
    "TLS_AES_128_GCM_SHA256",
    "TLS_AES_256_GCM_SHA384",
    "TLS_CHACHA20_POLY1305_SHA256",
}


@pytest.fixture()
def tls_dir(tmp_path: Path) -> Iterator[Path]:
    """§17.3 identity on disk in a tmp dir (cert.pem/key.pem, owner-only)."""
    directory = tmp_path / "tls"
    load_or_create_identity(directory)
    yield directory


def _serve_one_handshake(
    context: ssl.SSLContext, result: list[str | None], ready: threading.Event
) -> socket.socket:
    """Accept exactly ONE connection and handshake it server-side.

    On success appends the negotiated version string; on handshake failure
    appends None (the server must also see the failure — fail closed, never
    a silent downgrade). The listener socket is returned so the caller can
    close it deterministically after the client side finished; the accept
    thread is a daemon and never outlives the test.
    """
    listener = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    listener.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    listener.bind(("127.0.0.1", 0))
    listener.listen(1)
    listener.settimeout(10)
    ready.set()

    def _serve() -> None:
        try:
            conn, _ = listener.accept()
            try:
                tls_conn = context.wrap_socket(conn, server_side=True)
                result.append(tls_conn.version())
                tls_conn.sendall(b"ok")
                tls_conn.close()
            except (ssl.SSLError, OSError):
                result.append(None)
        except (TimeoutError, OSError):
            result.append(None)

    threading.Thread(target=_serve, daemon=True).start()
    return listener


def _await_result(result: list[str | None], timeout: float = 5.0) -> str | None:
    """Bounded wait for the server thread's handshake verdict (no sleeps)."""
    deadline = time.monotonic() + timeout
    while not result and time.monotonic() < deadline:
        time.sleep(0.01)
    assert result, "server thread produced no handshake verdict in time"
    return result[0]


def _tls13_client_context() -> ssl.SSLContext:
    """Loopback test client — self-signed Agent identity is trusted by fiat
    (the App verifies the pin instead, §17.3; out of scope for this entry)."""
    context = ssl.create_default_context()
    context.check_hostname = False
    context.verify_mode = ssl.CERT_NONE
    context.minimum_version = ssl.TLSVersion.TLSv1_3
    return context


def test_tls13_handshake_succeeds(tls_dir: Path) -> None:
    """TLS 1.3 client: handshake OK, version "TLSv1.3", cipher ∈ TLS 1.3 suites."""
    result: list[str | None] = []
    ready = threading.Event()
    context = build_tls13_server_context(str(tls_dir / "cert.pem"), str(tls_dir / "key.pem"))
    listener = _serve_one_handshake(context, result, ready)
    try:
        assert ready.wait(5)
        port = listener.getsockname()[1]
        raw = socket.create_connection(("127.0.0.1", port), timeout=10)
        with _tls13_client_context().wrap_socket(raw, server_hostname="localmesh-agent") as conn:
            assert conn.version() == "TLSv1.3"
            assert conn.cipher() is not None
            assert conn.cipher()[0] in TLS13_CIPHERS
            assert conn.recv(2) == b"ok"
    finally:
        listener.close()
    assert _await_result(result) == "TLSv1.3"  # server side agrees


def test_tls12_client_rejected_at_handshake(tls_dir: Path) -> None:
    """TLS 1.2-only client: handshake must FAIL CLOSED on both sides (§17.3)."""
    result: list[str | None] = []
    ready = threading.Event()
    context = build_tls13_server_context(str(tls_dir / "cert.pem"), str(tls_dir / "key.pem"))
    listener = _serve_one_handshake(context, result, ready)
    try:
        assert ready.wait(5)
        port = listener.getsockname()[1]
        client_context = _tls13_client_context()
        client_context.maximum_version = ssl.TLSVersion.TLSv1_2  # pre-TLS-1.3 client
        with pytest.raises(ssl.SSLError):
            raw = socket.create_connection(("127.0.0.1", port), timeout=10)
            conn = client_context.wrap_socket(raw, server_hostname="localmesh-agent")
            conn.close()
    finally:
        listener.close()
    assert _await_result(result) is None  # server saw the rejection too


def test_production_context_pins_tls13_minimum(tls_dir: Path) -> None:
    """Config scan: `minimum_version` is TLSv1_3 — nothing older can be served."""
    context = build_tls13_server_context(str(tls_dir / "cert.pem"), str(tls_dir / "key.pem"))
    assert context.minimum_version == ssl.TLSVersion.TLSv1_3
